<script lang="ts">
	import Project from './project.svelte';
	interface Pjct {
		title: string;
		link: string;
		info: string;
		desc: string;
		skills: string;
	}
	let projects: Array<Pjct> = [
		{
			title: 'Stockbear',
			desc: 'Neural network written with no libraries in C++ aiming to distill stockfish',
			link: 'https://github.com/BeanyZoldyck/stockbear/tree/main?tab=readme-ov-file',
			info: 'this project got a B',
      skills: 'ai scratch'
		},
		{
			title: 'Obfuscryption',
			desc: "collection of cryptography scripts i've written",
			link: 'https://github.com/BeanyZoldyck/obfuscryption',
			info: '',
      skills: 'crypto'

		},
		{
			title: 'BabbleFish',
			desc: 'hackathon project that summarizes, translates, and semantically searches text channels',
			link: 'https://devpost.com/software/babelfetch',
			info: "it lost the Gemini track to a project that didn't use Gemini",
      skills: 'ai LLMs agents GUI'

		},
		{
			title: 'NameBot',
			desc: 'machine Learning library made with no libraries in python. example predicts gender of input name',
			link: 'https://github.com/BeanyZoldyck/NameBot',
			info: '',
      skills: 'ai scratch NLP'

		},
		{
			title: 'GenDaBot',
			desc: 'model trained on ~100,000 tweets to predict the gender of the author',
			link: 'https://github.com/BeanyZoldyck/GenDaBot',
			info: '',
      skills: 'ai NLP GUI data'

		},
		{
			title: 'LLM.c',
			desc: 'transformer architecture in C ',
			link: 'https://github.com/BeanyZoldyck/llm.c',
			info: 'WIP, currently implementing backpropagation',
      skills: 'ai NLP LLMs scratch'

		}, 
		{
			title: 'yolo-train',
			desc: 'GUI to assist in labeling a dataset to finetune a YOLO model with',
			link: 'https://github.com/BeanyZoldyck/yolo-train',
			info: '',
      skills: 'CV ai GUI'

		}, 
		{
			title: 'kardia digitizer',
			desc: 'Script to digitize pdfs generated by the KardiaMobile EKG and mobile app',
			link: 'https://github.com/BeanyZoldyck/kardia-digitization',
			info: 'forked general version and modified to work for Kardia mobile',
      skills: 'CV GUI data'

		}, 

	];
  const remove = (item, array) => {array.length > 1 ? array.splice(array.indexOf(item), 1): array = []}
  let skills: Array<string> = $state([]);
  const updateSkills = () => {
    filtered = [];
  const tempSkill = document.getElementById('tempskill').textContent;
  if  (skills.includes(tempSkill)) remove(tempSkill, skills);
  else {
      if (tempSkill) skills.push(tempSkill);
    }
    for (const pj of projects) {
      pj.skills.split(' ').forEach(sk => {if (sk && skills.includes(sk)) filtered.push(pj) });
    }

    for (const pj of projects) {
      pj.skills.split(' ').forEach(sk => {if (sk && skills.includes(sk)) filtered.push(pj) });
    }
    console.log(filtered)
  }

	let filtered: Array<Pjct> = $state([]);

</script>
<section class="py-20">
  <div class="grid grid-cols-2">
<h1 class="mb-8 text-4xl font-bold text-purple-300">projects</h1>
<p id='skillbank' onclick={()=>{skills = []; filtered = []}} class='text-white'>{#if (skills.length > 0)}filters: {/if}{' '+skills.join(', ')}</p>
</div>
	<div class="space-y-8" onclick={updateSkills}>
    {#if (skills.length == 0)}
		{#each projects.sort(() => Math.random() - 0.5) as project}
			<Project {project} ></Project>
		{/each}
    {:else}
		{#each filtered as project}
			<Project {project} ></Project>
		{/each}
{/if}
	</div>
<p id='tempskill' class='text-black w-0 h-0'>{skills}</p>
</section>
